// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnvnirejxixouxlazjcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxudm5pcmVqeGl4b3V4bGF6amNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NTcwMTEsImV4cCI6MjA0OTUzMzAxMX0.k_TUOg2zma-X_Hqh2QfDh55cMtQoke0WzoPDu_JB_Iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);